version: "2"

networks:
  gitea:
    external: false

services:
  gitea:
    image: gitea/gitea:latest
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - TZ=Asia/Tokyo
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea-data:/data
      #- /etc/timezone:/etc/timezone:ro
      #- /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "2222:22"

  drone:
    image: drone/drone:latest
    ports:
      - "3080:80"
    volumes:
      - ./drone-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Japan
      - DRONE_GIT_ALWAYS_AUTH=false
      - DRONE_RUNNER_CAPACITY=2
      #- DRONE_SERVER_HOST=${GITEA_SV_ADDR}:3080
      - DRONE_SERVER_HOST=192.168.1.58:3080
      - DRONE_SERVER_PROTO=http
      - DRONE_TLS_AUTOCERT=false
      #- DRONE_GITEA_SERVER=http://${GITEA_SV_ADDR}:3000
      - DRONE_GITEA_SERVER=http://192.168.1.58:3000
      - DRONE_GITEA_CLIENT_ID=12b10d41-775f-4f46-a438-946894dc095a
      - DRONE_GITEA_CLIENT_SECRET=j4rbYTmh59fpnJ4oWhxwX_s6DSyun2r1HCka28eV7Q0=
      - DRONE_RPC_SECRET=bea26a2221fd8090ea38720fc445eca6
    restart: always

  registry:
    image: registry:2
    volumes:
      - ./registry-auth:/auth
      - ./registry-certs:/certs
      - ./registry-data:/var/lib/registry
    ports:
      - "5000:5000"
    environment:
      #- REGISTRY_AUTH=htpasswd
      #- REGISTRY_AUTH_HTPASSWD_REALM="Registry Realm"
      #- REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
      - REGISTRY_HTTP_ADDR=0.0.0.0:5000
      #- REGISTRY_HTTP_TLS_CERTIFICATE=/certs/ca.crt
      #- REGISTRY_HTTP_TLS_KEY=/certs/ca.key
      - REGISTRY_STORAGE_DELETE_ENABLED=true
    restart: always

  web:
    depends_on:
      - registry
    image: parabuzzle/craneoperator:latest
    ports:
      - "3180:80"
    environment:
      - REGISTRY_HOST=registry
      - REGISTRY_PORT=5000
      #- REGISTRY_PROTOCOL=https
      - REGISTRY_PROTOCOL=http
      - SSL_VERIFY=false
      - REGISTRY_PUBLIC_URL=192.168.1.58
      - REGISTRY_USERNAME=username
      - REGISTRY_PASSWORD=password
      - USERNAME=username
      - PASSWORD=password
      - REGISTRY_ALLOW_DELETE=true
    restart: always

