version: "2"

services:
  gitea:
    image: gitea/gitea:latest
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - TZ=Asia/Tokyo
    volumes:
      #- ./gitea-data:/data
      - gitea-data:/data
    ports:
      - "3000:3000"
      - "2222:22"

volumes:
    gitea-data:
        driver: local

