version: "2"

services:
  sonarqube:
    image: sonarqube:7.9.1-community
    ports:
      - "9000:9000"
    networks:
      - sonarnet
    volumes:
      - ./data/sonarqube_data:/opt/sonarqube/data
      - ./data/sonarqube_extensions:/opt/sonarqube/extensions
      - ./data/sonarqube_logs:/opt/sonarqube/logs
      - ./data/sonarqube_temp:/opt/sonarqube/temp

networks:
  sonarnet:
    driver: bridge

